development:
  pool: 5
  url:
  env: "DATABASE_URL"
  unsafe: true

development_follower:
  pool: 5
  url:
  env: "DATABASE_URL"
  unsafe: true

staging:
  url:
  env: "DATABASE_URL"
  unsafe: true

staging_follower:
  url:
  env: "DATABASE_URL"
  unsafe: true

production:
  url:
  env: "DATABASE_URL"
  unsafe: true

production_follower:
  url:
  env: "DATABASE_URL_FOLLOWER"
  unsafe: true