basePath: /
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is an SMS server. You can visit the GitHub repository at https://github.com/olusola/go-backend
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Go SMS API
  version: "1.0"
paths:
  /api/inbound/sms:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: inbound handler
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
